experiment_name: 'lafite_img_gen'

logger:
    save_dir: '/pasteur/u/esui/data/logger/'
    project: 'lafite_img_gen'
    entity: 'elainesui'

encoder:
    clip_model_type: 'ViT-B/32'
    modality: 'vision' # 'vision' 'language'
    
decoder:
    modality: 'vision' # 'vision'

data: 
  dataset: 'coco'
  seed: 1234
  train_split: 'val' #'train+restval' # train, restval, train+restval
  train_data_path: '/pasteur/u/esui/data/coco/oscar_split_ViT-B_32_train.pkl'
  train_restval_data_path: '/pasteur/u/esui/data/coco/oscar_split_ViT-B_32_train+restval.pkl'
  val_data_path: '/pasteur/u/esui/data/coco/oscar_split_ViT-B_32_val.pkl'
  test_data_path: '/pasteur/u/esui/data/coco/oscar_split_ViT-B_32_test.pkl'
  out_dir: '/pasteur/u/esui/data/coco/clip_prefix_cap_refactored_ckpts'
